### ISSUE TITLE
Error caused by differences in ERA5 Data Between CDS and CDS-Beta

### ISSUE THREAD

**Issue by yurgaohku** [linjonathan/tropical_cyclone_risk#7]
Hi Lin,

The ERA5 CDS dataset is scheduled to be replaced by the CDS-Beta dataset starting from 26 September 2024. More information can be found here: (https://forum.ecmwf.int/t/differences-in-era5-pressure-level-data-between-cds-and-cds-beta/5014). When I attempt to use the new CDS-Beta data to run the `run.py` file, I encountered the following error:

> Saving model output to /home/yurgao/tc/tropical_cyclone_risk-main/data/era5/test/
> Generating land masks...
> Computing monthly mean and variance of environmental wind...
> Traceback (most recent call last):
>   File "/home/yurgao/.conda/envs/tc_risk/lib/python3.12/site-packages/xarray/core/dataset.py", line 1393, in _construct_dataarray
>     variable = self._variables[name]
>                ~~~~~~~~~~~~~~~^^^^^^
> KeyError: 'time'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/home/yurgao/tc/tropical_cyclone_risk-main/run.py", line 15, in <module>
>     compute.compute_downscaling_inputs()
>   File "/home/yurgao/tc/tropical_cyclone_risk-main/util/compute.py", line 27, in compute_downscaling_inputs
>     env_wind.gen_wind_mean_cov()
>   File "/home/yurgao/tc/tropical_cyclone_risk-main/track/env_wind.py", line 97, in gen_wind_mean_cov
>     out = dask.compute(*lazy_results)
>           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/yurgao/.conda/envs/tc_risk/lib/python3.12/site-packages/dask/base.py", line 664, in compute
>     results = schedule(dsk, keys, **kwargs)
>               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/yurgao/tc/tropical_cyclone_risk-main/track/env_wind.py", line 130, in wnd_stat_wrapper
>     dts = input.convert_to_datetime(ds_ua, ds_ua['time'].values)
>                                            ~~~~~^^^^^^^^
>   File "/home/yurgao/.conda/envs/tc_risk/lib/python3.12/site-packages/xarray/core/dataset.py", line 1484, in __getitem__
>     return self._construct_dataarray(key)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/yurgao/.conda/envs/tc_risk/lib/python3.12/site-packages/xarray/core/dataset.py", line 1395, in _construct_dataarray
>     _, name, variable = _get_virtual_variable(self._variables, name, self.dims)
>                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/yurgao/.conda/envs/tc_risk/lib/python3.12/site-packages/xarray/core/dataset.py", line 196, in _get_virtual_variable
>     raise KeyError(key)
> KeyError: 'time'

It appears that the issue may be due to differences in data output between the old CDS and the CDS-Beta. For more details, you might find this report helpful: (https://forum.ecmwf.int/t/differences-in-era5-pressure-level-data-between-cds-and-cds-beta/5014). Would it be possible for you to make adjustments to the existing model code to better align with the new dataset? 

Best,
Gao

**Comment by linjonathan** [comment]
Hi Gao,

Yes, this is an issue since the conversion from .grib to .netcdf seems to have changed on the ERA5 server. I will be adding support for .grib files in the near future.

Jonathan

**Comment by XinghanLiu2002** [comment]
Hi @linjonathan,

Thanks for your open-source model. I am experiencing the same problem and would like to know if you have resolved this issue. 

Best wishes,
Xinghan

**Comment by XinghanLiu2002** [comment]
Hi Jonathan。

Thanks for your open source model !
I am experiencing the same error, and I would like to know if you have solved this issue.

Best wishes,
Xinghan

**Comment by linjonathan** [comment]
@XinghanLiu2002 @yurgaohku  @alexandrefierro

Please see [this pull request](https://github.com/linjonathan/tropical_cyclone_risk/pull/11) for code changes. If there are no issues, I will merge it. Note, you will need to re-download the ERA5 data in the GRIB format, using the updated `download_era5.py` script.

**Comment by XinghanLiu2002** [comment]
Thank you jonathan!
When I downloaded the ERA5 data by updated `download_era5.py` , though the target data were successfully downloaded to the `data/era5` file, it still had a strange output as following.
```
[Forum announcement](https://forum.ecmwf.int/t/final-validated-era5-product-to-differ-from-era5t-in-july-2024/6685)
for details and watch it for further updates on this.
2024-11-28 10:07:16,018 INFO Request ID is f1e2f3e0-604d-49d5-a7a1-e8d670e5641e
2024-11-28 10:07:16,305 INFO status has been updated to accepted
2024-11-28 10:07:25,390 INFO status has been updated to successful
Error downloading the data...  
```
Then I ran `python3 run.py WP` (because I only need TCs in WP), the error occurred as following. 
```
Saving model output to /work/home/xinghan/tc/tc_risk/data/era5/test/
Generating land masks...
Preprocessing .grib files...
Traceback (most recent call last):
  File "/work/home/xinghan/tc/tc_risk/run.py", line 15, in <module>
    compute.compute_downscaling_inputs()
  File "/work/home/xinghan/tc/tc_risk/util/compute.py", line 27, in compute_downscaling_inputs
    input.preprocess_grib()
  File "/work/home/xinghan/tc/tc_risk/util/input.py", line 23, in preprocess_grib
    ds = xr.open_dataset(fn)
         ^^^^^^^^^^^^^^^^^^^
  File "/work/home/xinghan/miniconda3/envs/tc_risk/lib/python3.11/site-packages/xarray/backends/api.py", line 547, in open_dataset
    engine = plugins.guess_engine(filename_or_obj)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/work/home/xinghan/miniconda3/envs/tc_risk/lib/python3.11/site-packages/xarray/backends/plugins.py", line 197, in guess_engine
    raise ValueError(error_msg)
ValueError: did not find a match in any of xarray's currently installed IO backends ['netcdf4', 'scipy']. Consider explicitly selecting one of the installed engines via the ``engine`` parameter, or installing additional IO dependencies, see:
https://docs.xarray.dev/en/stable/getting-started-guide/installing.html
https://docs.xarray.dev/en/stable/user-guide/io.html
```
It seems that there are somethings wrong in python packages.
And then I checked the version of the two packages.
```
netcdf4                   1.6.2           py311h0e679e6_0    defaults
scipy                     1.14.1          py311h08b1b3b_0    defaults
```
Whether we need to modify the `environment.yml` after we updated the scripts as you mentioned.

**Comment by linjonathan** [comment]
Doesn't your output say "Error downloading the data..."?

**Comment by XinghanLiu2002** [comment]
Yes, but the data did get downloaded.  
`(base) [xinghan@login03 era5]$ find -type f -name "*.grib"

./2021/era5_t_monthly_2021.grib
./2021/era5_q_monthly_2021.grib
./2021/era5_v_daily_2021.grib
./2021/era5_sst_monthly_2021.grib
./2021/era5_sp_monthly_2021.grib
./2021/era5_u_daily_2021.grib
./2016/era5_sst_monthly_2016.grib
./2016/era5_u_daily_2016.grib
./2016/era5_sp_monthly_2016.grib
./2016/era5_t_monthly_2016.grib
./2016/era5_q_monthly_2016.grib
./2016/era5_v_daily_2016.grib
./2019/era5_sst_monthly_2019.grib
./2019/era5_sp_monthly_2019.grib
./2019/era5_t_monthly_2019.grib
./2019/era5_q_monthly_2019.grib
./2019/era5_u_daily_2019.grib
./2019/era5_v_daily_2019.grib
./2018/era5_sst_monthly_2018.grib
./2018/era5_sp_monthly_2018.grib
./2018/era5_u_daily_2018.grib
./2018/era5_t_monthly_2018.grib
./2018/era5_q_monthly_2018.grib
./2018/era5_v_daily_2018.grib
./2020/era5_t_monthly_2020.grib
./2020/era5_q_monthly_2020.grib
./2020/era5_u_daily_2020.grib
./2020/era5_sst_monthly_2020.grib
./2020/era5_sp_monthly_2020.grib
./2020/era5_v_daily_2020.grib
./2017/era5_t_monthly_2017.grib
./2017/era5_q_monthly_2017.grib
./2017/era5_u_daily_2017.grib
./2017/era5_sst_monthly_2017.grib
./2017/era5_sp_monthly_2017.grib
./2017/era5_v_daily_2017.grib`

ERA5 official website shows that the download has been completed so I feel strange about `Error downloading the data...  `.
![image](https://github.com/user-attachments/assets/15bde0b2-da5b-4190-a3e0-579e5823100f)
Yet, I download all the data locally and upload them to the cluster to run `python3 run.py WP` next.
Either way, I still end up with the above error.

**Comment by alexandrefierro** [comment]
> @XinghanLiu2002 @yurgaohku @alexandrefierro
> 
> Please see [this pull request](https://github.com/linjonathan/tropical_cyclone_risk/pull/11) for code changes. If there are no issues, I will merge it. Note, you will need to re-download the ERA5 data in the GRIB format, using the updated `download_era5.py` script.

Hi Jonathan: 

I was lucky enough to retrieve all the data I needed prior to this nomenclature change from ECMWF. So no issues on my end.
A naive idea but would it be simpler to just change the array name valid_time to time using NETCDF tools such as CDO or NCO?

NCO:
ncrename -v valid_time,time input.nc output.nc
CDO:
cdo chname,valid_time,time input.nc output.nc

Cheers,

**Comment by linjonathan** [comment]
> Yes, but the data did get downloaded. `(base) [xinghan@login03 era5]$ find -type f -name "*.grib"
> 
> ./2021/era5_t_monthly_2021.grib ./2021/era5_q_monthly_2021.grib ./2021/era5_v_daily_2021.grib ./2021/era5_sst_monthly_2021.grib ./2021/era5_sp_monthly_2021.grib ./2021/era5_u_daily_2021.grib ./2016/era5_sst_monthly_2016.grib ./2016/era5_u_daily_2016.grib ./2016/era5_sp_monthly_2016.grib ./2016/era5_t_monthly_2016.grib ./2016/era5_q_monthly_2016.grib ./2016/era5_v_daily_2016.grib ./2019/era5_sst_monthly_2019.grib ./2019/era5_sp_monthly_2019.grib ./2019/era5_t_monthly_2019.grib ./2019/era5_q_monthly_2019.grib ./2019/era5_u_daily_2019.grib ./2019/era5_v_daily_2019.grib ./2018/era5_sst_monthly_2018.grib ./2018/era5_sp_monthly_2018.grib ./2018/era5_u_daily_2018.grib ./2018/era5_t_monthly_2018.grib ./2018/era5_q_monthly_2018.grib ./2018/era5_v_daily_2018.grib ./2020/era5_t_monthly_2020.grib ./2020/era5_q_monthly_2020.grib ./2020/era5_u_daily_2020.grib ./2020/era5_sst_monthly_2020.grib ./2020/era5_sp_monthly_2020.grib ./2020/era5_v_daily_2020.grib ./2017/era5_t_monthly_2017.grib ./2017/era5_q_monthly_2017.grib ./2017/era5_u_daily_2017.grib ./2017/era5_sst_monthly_2017.grib ./2017/era5_sp_monthly_2017.grib ./2017/era5_v_daily_2017.grib`
> 
> ERA5 official website shows that the download has been completed so I feel strange about `Error downloading the data... `. ![image](https://private-user-images.githubusercontent.com/183057094/390972177-15bde0b2-da5b-4190-a3e0-579e5823100f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI4ODc2NTQsIm5iZiI6MTczMjg4NzM1NCwicGF0aCI6Ii8xODMwNTcwOTQvMzkwOTcyMTc3LTE1YmRlMGIyLWRhNWItNDE5MC1hM2UwLTU3OWU1ODIzMTAwZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyOVQxMzM1NTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZmNmYzcxY2UyMGE5OGUyMzQ1ZjllOTdhNWMyODAxMzZkYWRkMWUxNTA5MjA0YTQ4MDUzY2I5ODFiZDM2MDk2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.cACQ4Fi7qxj27tCzBWWlR9XsNEtL62rTsuNPwjWoxqM) Yet, I download all the data locally and upload them to the cluster to run `python3 run.py WP` next. Either way, I still end up with the above error.

Ah, yes you probably need to install cfgrib. I can make those changes to the environment.yml file.
You can do this quickly by doing:

`conda install -n ENV_NAME eccodes cfgrib`

You can check commits d5cfcf8 ee17415 for changes to the conda environment.

**Comment by linjonathan** [comment]
> > @XinghanLiu2002 @yurgaohku @alexandrefierro
> > Please see [this pull request](https://github.com/linjonathan/tropical_cyclone_risk/pull/11) for code changes. If there are no issues, I will merge it. Note, you will need to re-download the ERA5 data in the GRIB format, using the updated `download_era5.py` script.
> 
> Hi Jonathan:
> 
> I was lucky enough to retrieve all the data I needed prior to this nomenclature change from ECMWF. So no issues on my end. A naive idea but would it be simpler to just change the array name valid_time to time using NETCDF tools such as CDO or NCO?
> 
> NCO: ncrename -v valid_time,time input.nc output.nc CDO: cdo chname,valid_time,time input.nc output.nc
> 
> Cheers,

This isn't actually an issue with the code; it is that the grib to netcdf conversion script on the CDS server changes the time variable. I think grib is the better format anyway, which is why I am adding grib support rather than writing a workaround for this issue. Most climate models still use netcdf output however.

**Comment by XinghanLiu2002** [comment]
> > Yes, but the data did get downloaded. `(base) [xinghan@login03 era5]$ find -type f -name "*.grib"
> > ./2021/era5_t_monthly_2021.grib ./2021/era5_q_monthly_2021.grib ./2021/era5_v_daily_2021.grib ./2021/era5_sst_monthly_2021.grib ./2021/era5_sp_monthly_2021.grib ./2021/era5_u_daily_2021.grib ./2016/era5_sst_monthly_2016.grib ./2016/era5_u_daily_2016.grib ./2016/era5_sp_monthly_2016.grib ./2016/era5_t_monthly_2016.grib ./2016/era5_q_monthly_2016.grib ./2016/era5_v_daily_2016.grib ./2019/era5_sst_monthly_2019.grib ./2019/era5_sp_monthly_2019.grib ./2019/era5_t_monthly_2019.grib ./2019/era5_q_monthly_2019.grib ./2019/era5_u_daily_2019.grib ./2019/era5_v_daily_2019.grib ./2018/era5_sst_monthly_2018.grib ./2018/era5_sp_monthly_2018.grib ./2018/era5_u_daily_2018.grib ./2018/era5_t_monthly_2018.grib ./2018/era5_q_monthly_2018.grib ./2018/era5_v_daily_2018.grib ./2020/era5_t_monthly_2020.grib ./2020/era5_q_monthly_2020.grib ./2020/era5_u_daily_2020.grib ./2020/era5_sst_monthly_2020.grib ./2020/era5_sp_monthly_2020.grib ./2020/era5_v_daily_2020.grib ./2017/era5_t_monthly_2017.grib ./2017/era5_q_monthly_2017.grib ./2017/era5_u_daily_2017.grib ./2017/era5_sst_monthly_2017.grib ./2017/era5_sp_monthly_2017.grib ./2017/era5_v_daily_2017.grib`
> > ERA5 official website shows that the download has been completed so I feel strange about `Error downloading the data... `. ![image](https://private-user-images.githubusercontent.com/183057094/390972177-15bde0b2-da5b-4190-a3e0-579e5823100f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI4ODc2NTQsIm5iZiI6MTczMjg4NzM1NCwicGF0aCI6Ii8xODMwNTcwOTQvMzkwOTcyMTc3LTE1YmRlMGIyLWRhNWItNDE5MC1hM2UwLTU3OWU1ODIzMTAwZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyOVQxMzM1NTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZmNmYzcxY2UyMGE5OGUyMzQ1ZjllOTdhNWMyODAxMzZkYWRkMWUxNTA5MjA0YTQ4MDUzY2I5ODFiZDM2MDk2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.cACQ4Fi7qxj27tCzBWWlR9XsNEtL62rTsuNPwjWoxqM) Yet, I download all the data locally and upload them to the cluster to run `python3 run.py WP` next. Either way, I still end up with the above error.
> 
> Ah, yes you probably need to install cfgrib. I can make those changes to the environment.yml file. You can do this quickly by doing:
> 
> `conda install -n ENV_NAME eccodes cfgrib`
> 
> You can check commits [d5cfcf8](https://github.com/linjonathan/tropical_cyclone_risk/commit/d5cfcf84372f1bb3446e10bf6adfbef4bdeab692) [ee17415](https://github.com/linjonathan/tropical_cyclone_risk/commit/ee1741530b88b1754b5b3ddf8c94f76e670e15cc) for changes to the conda environment.



```
(base) D:\tc\tropical_cyclone_risk-grib_update>conda env create -f environment.yml
Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound:
  - eccodes
  - cfgrib
```
I think `environment.yml` should add the following information for `eccodes` and `cfgrib`.
```
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip
  - pip:
    - eccodes
    - cfgrib
```

**Comment by alexandrefierro** [comment]
> > > @XinghanLiu2002 @yurgaohku @alexandrefierro
> > > Please see [this pull request](https://github.com/linjonathan/tropical_cyclone_risk/pull/11) for code changes. If there are no issues, I will merge it. Note, you will need to re-download the ERA5 data in the GRIB format, using the updated `download_era5.py` script.
> > 
> > 
> > Hi Jonathan:
> > I was lucky enough to retrieve all the data I needed prior to this nomenclature change from ECMWF. So no issues on my end. A naive idea but would it be simpler to just change the array name valid_time to time using NETCDF tools such as CDO or NCO?
> > NCO: ncrename -v valid_time,time input.nc output.nc CDO: cdo chname,valid_time,time input.nc output.nc
> > Cheers,
> 
> This isn't actually an issue with the code; it is that the grib to netcdf conversion script on the CDS server changes the time variable. I think grib is the better format anyway, which is why I am adding grib support rather than writing a workaround for this issue. Most climate models still use netcdf output however.

Hi Jonathan:

Do you know if this issue would also affect the CHAZ model from Chia-Ying Lee at Columbia Uni? I emailed them a few days ago but did not get a concrete response about that yet.

Could you also please elaborate on how exactly the time array changed with the CDS grib-->nc conversion through a quick example to see if this could be fixed with a simple NCO or CDO command? Thank you!

**Comment by linjonathan** [comment]
> > > Yes, but the data did get downloaded. `(base) [xinghan@login03 era5]$ find -type f -name "*.grib" ./2021/era5_t_monthly_2021.grib ./2021/era5_q_monthly_2021.grib ./2021/era5_v_daily_2021.grib ./2021/era5_sst_monthly_2021.grib ./2021/era5_sp_monthly_2021.grib ./2021/era5_u_daily_2021.grib ./2016/era5_sst_monthly_2016.grib ./2016/era5_u_daily_2016.grib ./2016/era5_sp_monthly_2016.grib ./2016/era5_t_monthly_2016.grib ./2016/era5_q_monthly_2016.grib ./2016/era5_v_daily_2016.grib ./2019/era5_sst_monthly_2019.grib ./2019/era5_sp_monthly_2019.grib ./2019/era5_t_monthly_2019.grib ./2019/era5_q_monthly_2019.grib ./2019/era5_u_daily_2019.grib ./2019/era5_v_daily_2019.grib ./2018/era5_sst_monthly_2018.grib ./2018/era5_sp_monthly_2018.grib ./2018/era5_u_daily_2018.grib ./2018/era5_t_monthly_2018.grib ./2018/era5_q_monthly_2018.grib ./2018/era5_v_daily_2018.grib ./2020/era5_t_monthly_2020.grib ./2020/era5_q_monthly_2020.grib ./2020/era5_u_daily_2020.grib ./2020/era5_sst_monthly_2020.grib ./2020/era5_sp_monthly_2020.grib ./2020/era5_v_daily_2020.grib ./2017/era5_t_monthly_2017.grib ./2017/era5_q_monthly_2017.grib ./2017/era5_u_daily_2017.grib ./2017/era5_sst_monthly_2017.grib ./2017/era5_sp_monthly_2017.grib ./2017/era5_v_daily_2017.grib`
> > > ERA5 official website shows that the download has been completed so I feel strange about `Error downloading the data... `. ![image](https://private-user-images.githubusercontent.com/183057094/390972177-15bde0b2-da5b-4190-a3e0-579e5823100f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI4ODc2NTQsIm5iZiI6MTczMjg4NzM1NCwicGF0aCI6Ii8xODMwNTcwOTQvMzkwOTcyMTc3LTE1YmRlMGIyLWRhNWItNDE5MC1hM2UwLTU3OWU1ODIzMTAwZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyOVQxMzM1NTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZmNmYzcxY2UyMGE5OGUyMzQ1ZjllOTdhNWMyODAxMzZkYWRkMWUxNTA5MjA0YTQ4MDUzY2I5ODFiZDM2MDk2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.cACQ4Fi7qxj27tCzBWWlR9XsNEtL62rTsuNPwjWoxqM) Yet, I download all the data locally and upload them to the cluster to run `python3 run.py WP` next. Either way, I still end up with the above error.
> > 
> > 
> > Ah, yes you probably need to install cfgrib. I can make those changes to the environment.yml file. You can do this quickly by doing:
> > `conda install -n ENV_NAME eccodes cfgrib`
> > You can check commits [d5cfcf8](https://github.com/linjonathan/tropical_cyclone_risk/commit/d5cfcf84372f1bb3446e10bf6adfbef4bdeab692) [ee17415](https://github.com/linjonathan/tropical_cyclone_risk/commit/ee1741530b88b1754b5b3ddf8c94f76e670e15cc) for changes to the conda environment.
> 
> ```
> (base) D:\tc\tropical_cyclone_risk-grib_update>conda env create -f environment.yml
> Collecting package metadata (repodata.json): done
> Solving environment: failed
> 
> ResolvePackageNotFound:
>   - eccodes
>   - cfgrib
> ```
> 
> I think `environment.yml` should add the following information for `eccodes` and `cfgrib`.
> 
> ```
> channels:
>   - conda-forge
>   - defaults
> dependencies:
>   - python=3.8
>   - pip
>   - pip:
>     - eccodes
>     - cfgrib
> ```

Yes, you're correct. Everything else working otherwise?

**Comment by linjonathan** [comment]
> > > > @XinghanLiu2002 @yurgaohku @alexandrefierro
> > > > Please see [this pull request](https://github.com/linjonathan/tropical_cyclone_risk/pull/11) for code changes. If there are no issues, I will merge it. Note, you will need to re-download the ERA5 data in the GRIB format, using the updated `download_era5.py` script.
> > > 
> > > 
> > > Hi Jonathan:
> > > I was lucky enough to retrieve all the data I needed prior to this nomenclature change from ECMWF. So no issues on my end. A naive idea but would it be simpler to just change the array name valid_time to time using NETCDF tools such as CDO or NCO?
> > > NCO: ncrename -v valid_time,time input.nc output.nc CDO: cdo chname,valid_time,time input.nc output.nc
> > > Cheers,
> > 
> > 
> > This isn't actually an issue with the code; it is that the grib to netcdf conversion script on the CDS server changes the time variable. I think grib is the better format anyway, which is why I am adding grib support rather than writing a workaround for this issue. Most climate models still use netcdf output however.
> 
> Hi Jonathan:
> 
> Do you know if this issue would also affect the CHAZ model from Chia-Ying Lee at Columbia Uni? I emailed them a few days ago but did not get a concrete response about that yet.
> 
> Could you also please elaborate on how exactly the time array changed with the CDS grib-->nc conversion through a quick example to see if this could be fixed with a simple NCO or CDO command? Thank you!

Sorry, I was not involved with the development of CHAZ.

Based on the files I downloaded, there were two main issues.
1) In the monthly-averaged files, the `time` variable was replaced with `date`, which is of type int64. If you can change the type to a datetime64 variable and the variable name to `time` (which should be relatively straightforward with xarray in Python), then it should work with the current version. I'm not familiar enough with NCO to know if you can do this easily.
2) In the daily wind files, the `time` variable was replaced with `valid_time`, which is the right type (datetime64). You just need to rename this variable to `time`. This is easily accomplished with NCO.

**Comment by alexandrefierro** [comment]
Thanks, Jonathan. In the daily ERA-5 files the type is: int64 valid_time(valid_time) ;  as netcdf is unable to support datetime64 formats. In short, NetCDF provides a way to represent date-time information using a numeric variable and an associated time units attribute. So any conversion to more modern formats such as datetime64 should be handled by Python using the native int64 format of netcdf. aka ERA-5 netcdf cannot offer datetime64 directly; same with GRIB2 as date there are stored as metadata. So there shouldn't be any code change for var types at read times other than changing variable names in the Python software?
For the ERA-5 "'product_type': 'monthly_averaged_reanalysis'" I also get: int64 valid_time(valid_time)? So note sure where you see "date" as a varname.

**Comment by linjonathan** [comment]
Ah, yes you're right.

OK, maybe something changed on the CDS server between when you and I downloaded the data. I'm afraid the CDS server is a bit clunky right now but they will probably work out the kinks in the near future.

Anyway, I do think that moving to .grib is the better option, at least when using the ERA5 reanalysis data.

**Comment by alexandrefierro** [comment]
Thank you Jonathan! Both CDS & MARS servers are notorious for being clunky and experiencing intermittent server issues. Their online service is also not very timely in terms of assisting paying customers (for MARS). In  20+ years of usage, I never had any issues with NOAA/GFS data & all of their products are free.

I prefer to stick with netcdf files as I find GRIB1,2 quite complicated to handle/read/visualize - ChatGPT is very helpful in that regard but I would prefer if your source code stick with netcdf, as it is a much more versatile and widely-used format in the research realm (and I would hope I speak for the majority of users :) ).

**Comment by linjonathan** [comment]
@alexandrefierro Yes, I understand where you are coming from. However, I am reluctant to make any changes as of now because the netCDF files served by CDS are not stable, as per this link:
https://confluence.ecmwf.int/display/CKB/GRIB+to+netCDF+conversion+on+new+CDS+and+ADS+systems

> As GRIB is the native format of most of the datasets produced by ECMWF, the format used in the netCDF files served by the CDS/ADS should not be considered a long-term stable format. Therefore, it is highly discouraged that these netCDF files are used in operational/downstream services as the standard is subject to change.

That being said, something that may be easy for me to do is to include a variable name for 'time'. Do you think that would solve your problems?

**Comment by alexandrefierro** [comment]
Hi Jonathan: Very useful information. Thank you! My version of the code works just fine as I retrieved the ERA-5 (netcdf) and code earlier this year before the CDS API changes. I was thinking out loud in terms of future implementation; whether I'd need to pull the new code and re-download all the ERA-5 data in grib format or simply add a few fixes to my existing code to accommodate the new netcdf formats.
On a side note, do you happen to know/work with Chia-Ying Lee & her team at CU? I would need some input data to run her CHAZ software as the data provided on her GIT repo is limited/incomplete (needs a standalone Matlab code to create the PI files for every single years, which is not provided). Thank you for any help you are able to provide on that front, if you are able.

**Comment by XinghanLiu2002** [comment]
> > > > Yes, but the data did get downloaded. `(base) [xinghan@login03 era5]$ find -type f -name "*.grib" ./2021/era5_t_monthly_2021.grib ./2021/era5_q_monthly_2021.grib ./2021/era5_v_daily_2021.grib ./2021/era5_sst_monthly_2021.grib ./2021/era5_sp_monthly_2021.grib ./2021/era5_u_daily_2021.grib ./2016/era5_sst_monthly_2016.grib ./2016/era5_u_daily_2016.grib ./2016/era5_sp_monthly_2016.grib ./2016/era5_t_monthly_2016.grib ./2016/era5_q_monthly_2016.grib ./2016/era5_v_daily_2016.grib ./2019/era5_sst_monthly_2019.grib ./2019/era5_sp_monthly_2019.grib ./2019/era5_t_monthly_2019.grib ./2019/era5_q_monthly_2019.grib ./2019/era5_u_daily_2019.grib ./2019/era5_v_daily_2019.grib ./2018/era5_sst_monthly_2018.grib ./2018/era5_sp_monthly_2018.grib ./2018/era5_u_daily_2018.grib ./2018/era5_t_monthly_2018.grib ./2018/era5_q_monthly_2018.grib ./2018/era5_v_daily_2018.grib ./2020/era5_t_monthly_2020.grib ./2020/era5_q_monthly_2020.grib ./2020/era5_u_daily_2020.grib ./2020/era5_sst_monthly_2020.grib ./2020/era5_sp_monthly_2020.grib ./2020/era5_v_daily_2020.grib ./2017/era5_t_monthly_2017.grib ./2017/era5_q_monthly_2017.grib ./2017/era5_u_daily_2017.grib ./2017/era5_sst_monthly_2017.grib ./2017/era5_sp_monthly_2017.grib ./2017/era5_v_daily_2017.grib`
> > > > ERA5 official website shows that the download has been completed so I feel strange about `Error downloading the data... `. ![image](https://private-user-images.githubusercontent.com/183057094/390972177-15bde0b2-da5b-4190-a3e0-579e5823100f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI4ODc2NTQsIm5iZiI6MTczMjg4NzM1NCwicGF0aCI6Ii8xODMwNTcwOTQvMzkwOTcyMTc3LTE1YmRlMGIyLWRhNWItNDE5MC1hM2UwLTU3OWU1ODIzMTAwZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyOVQxMzM1NTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZmNmYzcxY2UyMGE5OGUyMzQ1ZjllOTdhNWMyODAxMzZkYWRkMWUxNTA5MjA0YTQ4MDUzY2I5ODFiZDM2MDk2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.cACQ4Fi7qxj27tCzBWWlR9XsNEtL62rTsuNPwjWoxqM) Yet, I download all the data locally and upload them to the cluster to run `python3 run.py WP` next. Either way, I still end up with the above error.
> > > 
> > > 
> > > Ah, yes you probably need to install cfgrib. I can make those changes to the environment.yml file. You can do this quickly by doing:
> > > `conda install -n ENV_NAME eccodes cfgrib`
> > > You can check commits [d5cfcf8](https://github.com/linjonathan/tropical_cyclone_risk/commit/d5cfcf84372f1bb3446e10bf6adfbef4bdeab692) [ee17415](https://github.com/linjonathan/tropical_cyclone_risk/commit/ee1741530b88b1754b5b3ddf8c94f76e670e15cc) for changes to the conda environment.
> > 
> > 
> > ```
> > (base) D:\tc\tropical_cyclone_risk-grib_update>conda env create -f environment.yml
> > Collecting package metadata (repodata.json): done
> > Solving environment: failed
> > 
> > ResolvePackageNotFound:
> >   - eccodes
> >   - cfgrib
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I think `environment.yml` should add the following information for `eccodes` and `cfgrib`.
> > ```
> > channels:
> >   - conda-forge
> >   - defaults
> > dependencies:
> >   - python=3.8
> >   - pip
> >   - pip:
> >     - eccodes
> >     - cfgrib
> > ```
> 
> Yes, you're correct. Everything else working otherwise?

yes, I have no issue. Thanks for your reply!
